### ISSUE TITLE
Unable to build documentation

### ISSUE THREAD

**Issue by seweissman** [mbakeranalecta/spfe-open-toolkit#7]
I am trying to build the documentation as described in the README, but I am getting errors.
The build ultimately fails with this message:
<pre>
BUILD FAILED
/Users/sweissman/spfe-open-toolkit/spfe-ot/1.0/build-tools/spfe-rules.xml:517: The following error occurred while executing this line:
/Users/sweissman/spfebuild/spfebuild.xml:388: The following error occurred while executing this line:
/Users/sweissman/spfe-open-toolkit/spfe-ot/1.0/build-tools/spfe-rules.xml:366: /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/spfe-development/presentation-eppo/out/presentation.xml is not a valid XML document.
</pre>

There are other warning messages that are printed out as the build progresses, which I am including (part of) here. (I added a line to the spfe script that prints out SPFEOT_HOME.):
<pre>
SPFEOT_HOME : /Users/sweissman/spfe-open-toolkit/spfe-ot
Building in directory: /Users/sweissman/spfebuild
Buildfile: /Users/sweissman/spfebuild/spfebuild.xml

-begin-message:

=====================================================
Beginning draft build of spfe-docs
====================================================

-recorder:

-init:

-check-last-build-status:
Created dir: /Users/sweissman/spfebuild/spfe-docs/build/link-catalogs

draft:
Creating /Users/sweissman/spfebuild/spfe-docs/build/incomplete.flag

-draft-flag:
Creating /Users/sweissman/spfebuild/spfe-docs/build/draft.flag

--build.synthesis:
Building resolve for spfe-development.
Processing /Users/sweissman/spfebuild/spfe-docs/config/spfe-config.xml to /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/spfe-development/resolve.flag
Loading stylesheet /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/spfe-development/resolve/spfe.resolve.xsl
Warning: XML resolver not found; external catalogs will be ignored
Processing /Users/sweissman/spfebuild/spfe-docs/config/spfe-config.xml to /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/spfe-development/link-catalog.flag
Loading stylesheet /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/spfe-development/link-catalog/spfe.link-catalog.xsl
Warning: XML resolver not found; external catalogs will be ignored
Processing /Users/sweissman/spfebuild/spfe-docs/config/spfe-config.xml to /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/spfe-development/toc.flag
Loading stylesheet /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/spfe-development/toc/spfe.toc.xsl
Warning: XML resolver not found; external catalogs will be ignored
Info:  No toc file, using topic type order for online
Info:  Applying default TOC template to topics of type {http://spfeopentoolkit.org/ns/spfe-docs}think-plan-do-topic
Info:  Applying default TOC template to topics of type {http://spfeopentoolkit.org/ns/spfe-docs}generic-topic
Info:  Applying default TOC template to topics of type {http://spfeopentoolkit.org/ns/spfe-docs}feature-topic
Building resolve for spfe-docs-home.
Processing /Users/sweissman/spfebuild/spfe-docs/config/spfe-config.xml to /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/spfe-docs-home/resolve.flag
Loading stylesheet /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/spfe-docs-home/resolve/spfe.resolve.xsl
Warning: XML resolver not found; external catalogs will be ignored
Processing /Users/sweissman/spfebuild/spfe-docs/config/spfe-config.xml to /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/spfe-docs-home/link-catalog.flag
Loading stylesheet /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/spfe-docs-home/link-catalog/spfe.link-catalog.xsl
Warning: XML resolver not found; external catalogs will be ignored
Processing /Users/sweissman/spfebuild/spfe-docs/config/spfe-config.xml to /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/spfe-docs-home/toc.flag
Loading stylesheet /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/spfe-docs-home/toc/spfe.toc.xsl
Warning: XML resolver not found; external catalogs will be ignored
Info:  No toc file, using topic type order for online
Processing /Users/sweissman/spfebuild/spfe-docs/config/spfe-config.xml to /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/spfe-configuration-reference/extracted.flag
Loading stylesheet /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/spfe-configuration-reference/extract/spfe.extract.xsl
Warning: XML resolver not found; external catalogs will be ignored
Building merge for spfe-configuration-reference.
Processing /Users/sweissman/spfebuild/spfe-docs/config/spfe-config.xml to /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/spfe-configuration-reference/merge.flag
Loading stylesheet /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/spfe-configuration-reference/merge/spfe.merge.xsl
Warning: XML resolver not found; external catalogs will be ignored
Warning: Configuration setting description not found  /spfe/topic-set/topic-types/topic-type/name
Warning: Configuration setting description not found  /spfe/topic-set/object-types/object-type/name
Warning: Configuration setting description not found  /spfe/topic-type/name
Warning: Configuration setting description not found  /spfe/topic-type/scripts/merge
Warning: Configuration setting description not found  /spfe/topic-type/scripts/merge/script
Warning: Configuration setting description not found  /spfe/topic-type/scripts/merge/script/remap-namespace
Warning: Configuration setting description not found  /spfe/topic-type/scripts/merge/script/remap-namespace/from
Warning: Configuration setting description not found  /spfe/topic-type/scripts/merge/script/remap-namespace/to
Warning: Configuration setting description not found  /spfe/topic-type/scripts/merge/script/href
Warning: Configuration setting description not found  /spfe/topic-type/scripts/presentation/@type
Warning: Configuration setting description not found  /spfe/topic-type/scripts/format/@type
Warning: Configuration setting description not found  /spfe/object-type/name
Warning: Configuration setting description not found  /spfe/object-type/scripts/merge
Warning: Configuration setting description not found  /spfe/object-type/scripts/merge/script
Warning: Configuration setting description not found  /spfe/object-type/scripts/merge/script/remap-namespace
Warning: Configuration setting description not found  /spfe/object-type/scripts/merge/script/remap-namespace/from
Warning: Configuration setting description not found  /spfe/object-type/scripts/merge/script/remap-namespace/to
Warning: Configuration setting description not found  /spfe/object-type/scripts/merge/script/href
Warning: Configuration setting description not found  /spfe/object-type/scripts/presentation/@type
Warning: Configuration setting description not found  /spfe/object-type/scripts/format/@type
Warning: Configuration setting description not found  /spfe/output-format/@type
Warning: Configuration setting description not found  /spfe/output-format/scripts/merge
Warning: Configuration setting description not found  /spfe/output-format/scripts/merge/script
Warning: Configuration setting description not found  /spfe/output-format/scripts/merge/script/remap-namespace
Warning: Configuration setting description not found  /spfe/output-format/scripts/merge/script/remap-namespace/from
Warning: Configuration setting description not found  /spfe/output-format/scripts/merge/script/remap-namespace/to
Warning: Configuration setting description not found  /spfe/output-format/scripts/merge/script/href
Warning: Configuration setting description not found  /spfe/output-format/scripts/presentation/@type
Warning: Configuration setting description not found  /spfe/output-format/scripts/format/@type
Warning: Authored element description found for an element not found in the schema: /spfe/content-set/style
Warning: Authored element description found for an element not found in the schema: /spfe/object-type/xmlns
Warning: Authored element description found for an element not found in the schema: /spfe/topic-set/object-types/object-type/xmlns
Warning: Authored element description found for an element not found in the schema: /spfe/topic-set/topic-types/topic-type/xmlns
Warning: Authored element description found for an element not found in the schema: /spfe/topic-type/xmlns
Building resolve for spfe-configuration-reference.
Processing /Users/sweissman/spfebuild/spfe-docs/config/spfe-config.xml to /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/spfe-configuration-reference/resolve.flag
Loading stylesheet /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/spfe-configuration-reference/resolve/spfe.resolve.xsl
Warning: XML resolver not found; external catalogs will be ignored
Warning: Unknown or ambiguous SPFE config element name "xmlns". Context element is:/spfe/topic-set/topic-types/topic-type
Warning: Unknown or ambiguous SPFE config element name "xmlns". Context element is:/spfe/topic-set/object-types/object-type
Warning: Unknown or ambiguous SPFE config element name "/spfe/topic-type/scripts/format/@type". Context element is:/spfe/topic-set/output-formats/output-format/name
Processing /Users/sweissman/spfebuild/spfe-docs/config/spfe-config.xml to /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/spfe-configuration-reference/link-catalog.flag
Loading stylesheet /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/spfe-configuration-reference/link-catalog/spfe.link-catalog.xsl
Warning: XML resolver not found; external catalogs will be ignored
Processing /Users/sweissman/spfebuild/spfe-docs/config/spfe-config.xml to /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/spfe-configuration-reference/toc.flag
Loading stylesheet /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/spfe-configuration-reference/toc/spfe.toc.xsl
Warning: XML resolver not found; external catalogs will be ignored
Info:  No toc file, using topic type order for online
Processing /Users/sweissman/spfebuild/spfe-docs/config/spfe-config.xml to /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/eppo-presentation-doctype-reference/extracted.flag
Loading stylesheet /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/eppo-presentation-doctype-reference/extract/spfe.extract.xsl
Warning: XML resolver not found; external catalogs will be ignored
Building merge for eppo-presentation-doctype-reference.
Processing /Users/sweissman/spfebuild/spfe-docs/config/spfe-config.xml to /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/eppo-presentation-doctype-reference/merge.flag
Loading stylesheet /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/eppo-presentation-doctype-reference/merge/spfe.merge.xsl
Warning: XML resolver not found; external catalogs will be ignored
Warning: Doctype element description not found  title
Warning: Attribute description not found  /pages/page/@status
Warning: Attribute description not found  /pages/page/@type
Warning: Doctype element description not found  context-nav
Warning: Doctype element description not found  home
Warning: Attribute description not found  /pages/page/context-nav/home/xref/@class
Warning: Attribute description not found  /pages/page/context-nav/home/xref/@hint
Warning: Attribute description not found  /pages/page/context-nav/home/xref/@title
Warning: Attribute description not found  /pages/page/context-nav/home/xref/@topic-title
Warning: Attribute description not found  /pages/page/context-nav/home/xref/@topic-type
Warning: Doctype element description not found  breadcrumbs
Warning: Doctype element description not found  breadcrumb
Warning: Doctype element description not found  keywords
Warning: Doctype element description not found  keyword
Warning: Doctype element description not found  disambiguation
Warning: Doctype element description not found  p
Warning: Attribute description not found  /pages/page/context-nav/disambiguation/p/@hint
Warning: Doctype element description not found  xlink
Warning: Attribute description not found  /pages/page/context-nav/disambiguation/p/xlink/@href
Warning: Doctype element description not found  bold
Warning: Doctype element description not found  code
Warning: Doctype element description not found  italic
Warning: Attribute description not found  /pages/page/context-nav/disambiguation/p/name/@hint
Warning: Attribute description not found  /pages/page/context-nav/disambiguation/p/name/@type
Warning: Attribute description not found  /pages/page/context-nav/disambiguation/p/name/@hint
Warning: Attribute description not found  /pages/page/context-nav/disambiguation/p/name/@type
Warning: Doctype element description not found  related-nav
Warning: Doctype element description not found  categories
Warning: Doctype element description not found  category
Warning: Doctype element description not found  see-alsos
Warning: Doctype element description not found  see-also
Warning: Doctype element description not found  site-nav
Warning: Doctype element description not found  fig
Warning: Doctype element description not found  caption
Warning: Doctype element description not found  subhead
Warning: Doctype element description not found  anchor
Warning: Attribute description not found  /pages/page/site-nav/anchor/@name
Warning: Doctype element description not found  ol
Warning: Doctype element description not found  li
Warning: Doctype element description not found  ul
Warning: Doctype element description not found  codeblock
Warning: Attribute description not found  /pages/page/site-nav/codeblock/@language
Warning: Attribute description not found  /pages/page/site-nav/codeblock/@namespace
Warning: Doctype element description not found  title
Warning: Doctype element description not found  toc
Warning: Doctype element description not found  toc-entry
Warning: Doctype element description not found  byline
Warning: Doctype element description not found  by-label
Warning: Doctype element description not found  authors
Warning: Doctype element description not found  precis
Warning: Doctype element description not found  labeled-item
Warning: Doctype element description not found  label
Warning: Doctype element description not found  item
Warning: Doctype element description not found  tree
Warning: Attribute description not found  /pages/page/tree/@class
Warning: Doctype element description not found  branch
Warning: Attribute description not found  /pages/page/tree/branch/@state
Warning: Doctype element description not found  content
Warning: Doctype element description not found  section
Warning: Authored element description found for an element not found in the schema: 
Warning: Authored element description found for an element not found in the schema: 
Warning: Authored element description found for an element not found in the schema: 
Warning: Authored element description found for an element not found in the schema: 
Warning: Authored element description found for an element not found in the schema: 
Building resolve for eppo-presentation-doctype-reference.
Processing /Users/sweissman/spfebuild/spfe-docs/config/spfe-config.xml to /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/eppo-presentation-doctype-reference/resolve.flag
Loading stylesheet /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/eppo-presentation-doctype-reference/resolve/spfe.resolve.xsl
Warning: XML resolver not found; external catalogs will be ignored
Processing /Users/sweissman/spfebuild/spfe-docs/config/spfe-config.xml to /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/eppo-presentation-doctype-reference/link-catalog.flag
Loading stylesheet /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/eppo-presentation-doctype-reference/link-catalog/spfe.link-catalog.xsl
Warning: XML resolver not found; external catalogs will be ignored
Processing /Users/sweissman/spfebuild/spfe-docs/config/spfe-config.xml to /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/eppo-presentation-doctype-reference/toc.flag
Loading stylesheet /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/eppo-presentation-doctype-reference/toc/spfe.toc.xsl
Warning: XML resolver not found; external catalogs will be ignored
Info:  No toc file, using topic type order for online
Info:  Applying default TOC template to topics of type {http://spfeopentoolkit.org/ns/spfe-docs}doctype-reference-entry
Processing /Users/sweissman/spfebuild/spfe-docs/config/spfe-config.xml to /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/eppo-graphic-record-doctype-reference/extracted.flag
Loading stylesheet /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/eppo-graphic-record-doctype-reference/extract/spfe.extract.xsl
Warning: XML resolver not found; external catalogs will be ignored
Building merge for eppo-graphic-record-doctype-reference.
Processing /Users/sweissman/spfebuild/spfe-docs/config/spfe-config.xml to /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/eppo-graphic-record-doctype-reference/merge.flag
Loading stylesheet /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/eppo-graphic-record-doctype-reference/merge/spfe.merge.xsl
Warning: XML resolver not found; external catalogs will be ignored
Warning: Doctype element description not found  graphic-record
Warning: Doctype element description not found  name
Warning: Doctype element description not found  alt
Warning: Doctype element description not found  uri
Warning: Doctype element description not found  formats
Warning: Doctype element description not found  format
Warning: Doctype element description not found  type
Warning: Doctype element description not found  href
Warning: Doctype element description not found  height
Warning: Doctype element description not found  width
Warning: Doctype element description not found  dpi
Warning: Doctype element description not found  source
Warning: Doctype element description not found  credit
Warning: Doctype element description not found  default-title
Warning: Doctype element description not found  default-caption
Warning: Doctype element description not found  p
Building resolve for eppo-graphic-record-doctype-reference.
Processing /Users/sweissman/spfebuild/spfe-docs/config/spfe-config.xml to /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/eppo-graphic-record-doctype-reference/resolve.flag
Loading stylesheet /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/eppo-graphic-record-doctype-reference/resolve/spfe.resolve.xsl
Warning: XML resolver not found; external catalogs will be ignored
Processing /Users/sweissman/spfebuild/spfe-docs/config/spfe-config.xml to /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/eppo-graphic-record-doctype-reference/link-catalog.flag
Loading stylesheet /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/eppo-graphic-record-doctype-reference/link-catalog/spfe.link-catalog.xsl
Warning: XML resolver not found; external catalogs will be ignored
Processing /Users/sweissman/spfebuild/spfe-docs/config/spfe-config.xml to /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/eppo-graphic-record-doctype-reference/toc.flag
Loading stylesheet /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/eppo-graphic-record-doctype-reference/toc/spfe.toc.xsl
Warning: XML resolver not found; external catalogs will be ignored
Info:  No toc file, using topic type order for online
Info:  Applying default TOC template to topics of type {http://spfeopentoolkit.org/ns/spfe-docs}doctype-reference-entry
Processing /Users/sweissman/spfebuild/spfe-docs/config/spfe-config.xml to /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/eppo-generic-topic-doctype-reference/extracted.flag
Loading stylesheet /Users/sweissman/spfebuild/spfe-docs/build/topic-sets/eppo-generic-topic-doctype-reference/extract/spfe.extract.xsl
Warning: XML resolver not found; external catalogs will be ignored
/Users/sweissman/spfe-open-toolkit/spfe-docs/topic-types/doctype-reference/scripts/extract/schema-defs.xsl:70: Error! I/O error reported by XML parser processing http://spfeopentoolkit.org/spfe-ot/plugins/eppo-simple/topic-types/generic-topic/schemas/identity.xsd: http://spfeopentoolkit.org/spfe-ot/plugins/eppo-simple/topic-types/generic-topic/schemas/identity.xsd Cause: java.io.FileNotFoundException: http://spfeopentoolkit.org/spfe-ot/plugins/eppo-simple/topic-types/generic-topic/schemas/identity.xsd
/Users/sweissman/spfe-open-toolkit/spfe-docs/topic-types/doctype-reference/scripts/extract/schema-defs.xsl:70: Error! I/O error reported by XML parser processing http://spfeopentoolkit.org/spfe-ot/plugins/eppo-simple/topic-types/generic-topic/schemas/index.xsd: http://spfeopentoolkit.org/spfe-ot/plugins/eppo-simple/topic-types/generic-topic/schemas/index.xsd Cause: java.io.FileNotFoundException: http://spfeopentoolkit.org/spfe-ot/plugins/eppo-simple/topic-types/generic-topic/schemas/index.xsd
/Users/sweissman/spfe-open-toolkit/spfe-docs/topic-types/doctype-reference/scripts/extract/schema-defs.xsl:70: Error! I/O error reported by XML parser processing http://spfeopentoolkit.org/spfe-ot/plugins/eppo-simple/topic-types/generic-topic/schemas/tracking.xsd: http://spfeopentoolkit.org/spfe-ot/plugins/eppo-simple/topic-types/generic-topic/schemas/tracking.xsd Cause: java.io.FileNotFoundException: http://spfeopentoolkit.org/spfe-ot/plugins/eppo-simple/topic-types/generic-topic/schemas/tracking.xsd
/Users/sweissman/spfe-open-toolkit/spfe-docs/topic-types/doctype-reference/scripts/extract/schema-defs.xsl:70: Error! I/O error reported by XML parser processing http://spfeopentoolkit.org/spfe-ot/plugins/eppo-simple/topic-types/generic-topic/schemas/text-general.xsd: http://spfeopentoolkit.org/spfe-ot/plugins/eppo-simple/topic-types/generic-topic/schemas/text-general.xsd Cause: java.io.FileNotFoundException: http://spfeopentoolkit.org/spfe-ot/plugins/eppo-simple/topic-types/generic-topic/schemas/text-general.xsd
/Users/sweissman/spfe-open-toolkit/spfe-docs/topic-types/doctype-reference/scripts/extract/schema-defs.xsl:70: Error! I/O error reported by XML parser processing http://spfeopentoolkit.org/spfe-ot/plugins/eppo-simple/topic-types/generic-topic/schemas/conditions.xsd: http://spfeopentoolkit.org/spfe-ot/plugins/eppo-simple/topic-types/generic-topic/schemas/conditions.xsd Cause: java.io.FileNotFoundException: http://spfeopentoolkit.org/spfe-ot/plugins/eppo-simple/topic-types/generic-topic/schemas/conditions.xsd
/Users/sweissman/spfe-open-toolkit/spfe-docs/topic-types/doctype-reference/scripts/extract/schema-defs.xsl:70: Error! I/O error reported by XML parser processing http://spfeopentoolkit.org/spfe-ot/plugins/eppo-simple/topic-types/generic-topic/schemas/text-decoration.xsd: http://spfeopentoolkit.org/spfe-ot/plugins/eppo-simple/topic-types/generic-topic/schemas/text-decoration.xsd Cause: java.io.FileNotFoundException: http://spfeopentoolkit.org/spfe-ot/plugins/eppo-simple/topic-types/generic-topic/schemas/text-decoration.xsd
/Users/sweissman/spfe-open-toolkit/spfe-docs/topic-types/doctype-reference/scripts/extract/schema-defs.xsl:70: Error! I/O error reported by XML parser processing http://spfeopentoolkit.org/spfe-ot/plugins/eppo-simple/topic-types/generic-topic/schemas/annotations-general.xsd: http://spfeopentoolkit.org/spfe-ot/plugins/eppo-simple/topic-types/generic-topic/schemas/annotations-general.xsd Cause: java.io.FileNotFoundException: http://spfeopentoolkit.org/spfe-ot/plugins/eppo-simple/topic-types/generic-topic/schemas/annotations-general.xsd
/Users/sweissman/spfe-open-toolkit/spfe-docs/topic-types/doctype-reference/scripts/extract/schema-defs.xsl:70: Error! I/O error reported by XML parser processing http://spfeopentoolkit.org/spfe-ot/plugins/eppo-simple/topic-types/generic-topic/schemas/resources.xsd: http://spfeopentoolkit.org/spfe-ot/plugins/eppo-simple/topic-types/generic-topic/schemas/resources.xsd Cause: java.io.FileNotFoundException: http://spfeopentoolkit.org/spfe-ot/plugins/eppo-simple/topic-types/generic-topic/schemas/resources.xsd
</pre>

**Comment by mbakeranalecta** [comment]
The move from ANT to Python for the build makes this issue moot.
